### ISSUE TITLE
Hindi Numeric text is shown in the report.

### ISSUE THREAD

**Issue by Sandynaidu** [amank22/ApkSize-Analyzer#35]
Hindi Numeric text is shown in the report. can we get the updated jar file with English Numeric value showing. currently due to giveFormattedNumberText conversion in to HINDI numbers in HTMLGenerator kt file. 
<img width="1088" alt="Screenshot 2022-06-01 at 3 13 01 PM" src="https://user-images.githubusercontent.com/20302516/171377151-a0e3672c-6c0d-428b-a033-b0a7d70c81ff.png">

**Comment by Sandynaidu** [comment]
Can you please create an new .jar file may be with verison 0.3 and added it please

**Comment by amank22** [comment]
Hi, I just need to verify the changes, will be released soon in a day or two.

**Comment by Sandynaidu** [comment]
Thanks for Swift reply.
